### ISSUE TITLE
Performance compare to tensorflow 

### ISSUE THREAD

**Issue by llj098** [codinfox/espresso#1]
Hello,

Thanks for your work, it is quite interesting and exciting.

But on your home page, I only found the performance result compare with naive implementation, have you guys compared your performance with tensorflow ?

Thanks.

**Comment by codinfox** [comment]
Thank you for your interest. This project is only an experimental implementation for learning purposes. The performance is pretty bad compared with Tensorflow mobile. Tensorflow's official demo can already achieve close to realtime recognition with Inception-v1, ours is still far from that. So if you are looking for a production ready software, this is not what you want.
