### ISSUE TITLE
Extending this project to compare energy impact and adding Inception to the networks

### ISSUE THREAD

**Issue by Klamath233** [codinfox/espresso#2]
Hi Zhihao,

I am taking a course on energy-aware embedded systems. I'm proposing a project that will measure and compare the performance of CPU and GPU implementations of NNs. During research, I found Espresso could be a really great point for me to start, because it's really hard to find naive and easily understandable implementations in production systems (like TensorFlow Mobile). Espresso is a minimal  system that includes both naive CPU and GPU implementations of components of a CNN. I think I could contribute to the project in such steps:

1. Port the project to Swift 3;
2. Implement a new network (maybe Inception) using the layers;
3. Create a report on comparison of energy impact of different implementations.

Would you allow me to use your project as a starting point and do you think my proposal is doable?

Thanks,
Xi

**Comment by codinfox** [comment]
We are happy that you find Espresso useful. At least for me, your project seems interesting (and I bet @jerryzh168 would agree). Espresso is intended for educational purposes, so you are welcomed to use it in your own project. One catch is the GPU implementation of LRN currently is buggy... Don't forget to submit a pull request when you finish 👍 .

**Comment by Klamath233** [comment]
Thanks! I will keep these in mind.

**Comment by jerryzh168** [comment]
I think both of the CPU and GPU implementation of LRN layer are still buggy.. You can verify this by writing small test cases [here](https://github.com/codinfox/espresso/blob/master/espresso/espressoTests/LrnLayerTests.swift).

**Comment by Klamath233** [comment]
@jerryzh168 Thank you for pointing this out. Did you get any chance to locate the bugs? How did you bypass/mitigate this when you came up with your tests and report?

**Comment by jerryzh168** [comment]
Seems that CPU version is correct..but I'm not sure. Since we implemented LRN in the last minute, we don't have time to debug the correctness. In the end, the GPU version seems to be unstable and we didn't spot the bug, however, we still believe the performance measure should be similar when we have a stable version.

**Comment by Klamath233** [comment]
Got it. Thanks. It can be seen from the extent of the project that it must take monstrous amount of time to develop and test. So much respect to you guys 👍

**Comment by Klamath233** [comment]
Hi guys, here comes questions again. How did you generate the .espressomodel file? Is that a trained model?

**Comment by codinfox** [comment]
That's just a serialized swift array. You can dump Caffe models weights to npy, and use <https://github.com/codinfox/npy2swift> to convert the npy to swift array.

Look at <https://github.com/codinfox/espresso/blob/master/espresso/espresso/Network%2BImport.swift#L25> for details.

**Comment by Klamath233** [comment]
Thanks. Some more questions...

With regard to the LRN bug. I've seen in the code that you use a ReLU layer in the place of the LRN layer for AlexNet. Is that the bug you mentioned in a previous post?

```swift
    // LRN layer here
    //        network.add(LRNLayer(parameters: LRNParameters(
    //          name: "norm1",
    //          dependencies: ["relu_conv1"])))

     network.add(ReluLayer(parameters: ReLUParameters(
       name: "norm1",
       dependencies: ["relu_conv1"])))
```
Even when the above-mentioned workaround is in place, GPU version of AlexNet seems not to work while CPU version of it returns something meaningful. Were you experiencing this issue when you did the test?

![Alex_GPU](https://cloud.githubusercontent.com/assets/3377836/23976314/161bf8d0-09a4-11e7-9d42-f94c41fded17.jpeg)

![Alex_CPU](https://cloud.githubusercontent.com/assets/3377836/23976316/1aed050c-09a4-11e7-94f7-e8a9027905da.jpeg)

**Comment by Klamath233** [comment]
And after I look at the importFile method, I find that it's actually a serialized dictionary. The tool you provide only support arrays. Could you show me how you do the conversion for SqueezeNet?

**Comment by jerryzh168** [comment]
About debugging, I don't remember the details but generally you can write small test cases and execute step by step with XCode and see if all the intermediate results matches your expectation.

**Comment by Klamath233** [comment]
Thank you, Jerry. How about the model file generation/conversion? Correct me if I'm wrong: I think npy2swift only supports arrays. 

```swift
public func npy2array<T>(_ filename: String, sample: T) -> [T]
```

But the file import method actually decodes a dictionary from the .espressomodel file. How did you guys fill the gap?

**Comment by codinfox** [comment]
You are correct. It only supports arrays. What you need to do is to write a script to dump weights from caffe, translate them to swift array and then create swift dictionary based on the arrays. Sorry I didn't make this clearer. I remember to have a script to do that but cannot find it anymore.

**Comment by Klamath233** [comment]
Got it. Thanks!
